//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarCalculator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalendarCalculator.WinFormStrings", typeof(WinFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автозапуск.
        /// </summary>
        internal static string autorun {
            get {
                return ResourceManager.GetString("autorun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертер.
        /// </summary>
        internal static string converter {
            get {
                return ResourceManager.GetString("converter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to День.
        /// </summary>
        internal static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертер дат УЕХ.
        /// </summary>
        internal static string form_title {
            get {
                return ResourceManager.GetString("form_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подсчёт N-ой хелиады (1000 дней) для указанной даты.
        /// </summary>
        internal static string heliada_tab_info {
            get {
                return ResourceManager.GetString("heliada_tab_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хелиады.
        /// </summary>
        internal static string heliadas {
            get {
                return ResourceManager.GetString("heliadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат.
        /// </summary>
        internal static string invalid_format {
            get {
                return ResourceManager.GetString("invalid_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Беларуская.
        /// </summary>
        internal static string lang_be {
            get {
                return ResourceManager.GetString("lang_be", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string lang_ru {
            get {
                return ResourceManager.GetString("lang_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запускать свёрнутым.
        /// </summary>
        internal static string minimized {
            get {
                return ResourceManager.GetString("minimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подсказка.
        /// </summary>
        internal static string tooltip_title {
            get {
                return ResourceManager.GetString("tooltip_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат даты должен быть I.II.IV.X.
        /// </summary>
        internal static string tooltip_tut_input {
            get {
                return ResourceManager.GetString("tooltip_tut_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Двойной клик по этой дате скопирует её в буфер обмена.
        /// </summary>
        internal static string tooltip_tut_label {
            get {
                return ResourceManager.GetString("tooltip_tut_label", resourceCulture);
            }
        }
    }
}
